services:
  tjan-elements:
    container_name: tjan-elements
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./credentials.json:/credentials.json
      - ./token.json:/token.json
